# Weights and biases
wandb_run: True

# Directory structure
base_dir: '../CPSC532W_hw3' # NOTE: This path should be relative to the daphne path!
daphne_dir: '../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
probabilistic_tests: []
HW3_programs: [1,2,5]

# Daphne (re)compilation
compile: False

# Evaluation method
# mode: 'desugar'
mode: 'graph'

# Inference
num_samples: 1e3



# MH methods
method:  'HMC' #"HMC" # "MHG" # or "IS"
